#
# Copyright (C) 2013-2014, Nanjing WFNEX Technology Co., Ltd
# Author Yi Jian, yijian@wfnex.com
#
include $(USER_DEPTH)/make/makeinclude/wf_pre.mak
USER_SUB_DIRS= kwfnovs
include $(USER_DEPTH)/make/makeinclude/wf_post.mak
